# Generated by Django 5.2.3 on 2025-06-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotadb',
            name='id_dueno',
        ),
        migrations.AddField(
            model_name='mascotadb',
            name='documento_dueno',
            field=models.CharField(default='00000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duenodb',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
