# Generated by Django 5.2.3 on 2025-06-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0002_remove_mascotadb_id_dueno_mascotadb_documento_dueno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=200)),
                ('id_mascota', models.IntegerField()),
                ('activo', models.CharField(choices=[('s', 'Sí'), ('n', 'No')], max_length=1)),
            ],
        ),
    ]
