# Generated by Django 5.2.3 on 2025-06-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0003_consultadb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenodb',
            name='activo',
            field=models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='s', max_length=1),
        ),
    ]
